# When making changes to this file update requirements.txt also !!
# Usage:
# conda -v env update --file environment.yml; pre-commit run --all-files; pycheck

name: pylywsdxx

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pre-commit
  # Not on conda channels:
  - pip:
    - pylint>=3.0.2
    - bluepy3
